### ISSUE TITLE
Fixes para adicionar lesson

### ISSUE THREAD

**Issue by DavideCarvalho** [NewSchoolApp/newschool-backend#121]
- Tipar o Body explicitamente com NewLessonDTO
- O atributo course dentro do NewLessonDTO deve se chamar courseId para refletir o que ele realmente é
- O atributo course dentro do NewLessonDTO está como Course, e não como string
- Precisamos validar se o courseId é de um curso que está com enabled true

**Comment by pethersonmoreno** [comment]
Já está em pre-develop
