### ISSUE TITLE
Fixes para checar o test

### ISSUE THREAD

**Issue by DavideCarvalho** [NewSchoolApp/newschool-backend#129]
- o id deve vir antes do checkTest, ou seja, /:id/checkTest/
- Adicionar alternative a url antes do id da alternative, ficando /:id/checkTest/alternative/:chosenAlternative
- usar hifen invés de camel case no checkTest, ficando check-test
- Retirar `` ? true : false ``, ficando só `` test.correctAlternative === chosenAlternative ``
- Usar método existente ``findById`` que está no service invés de chamar o repositório novamente

**Comment by pethersonmoreno** [comment]
Já está em pre-develop
