### ISSUE TITLE
Não consegui logar com mídias sociais.

### ISSUE THREAD

**Issue by raffacabofrio** [NewSchoolApp/newschool-backend#149]
Tentei Google e Facebook. Ambos apresentaram erro.

![Screenshot_2020-01-29-00-05-38-105_com android chrome](https://user-images.githubusercontent.com/10622114/73324903-54aef300-422b-11ea-8917-f805ff8e6c91.jpg)

**Comment by pethersonmoreno** [comment]
Em ambiente de produção já está resolvido, só falta forçar sempre abrir em HTTPS

**Comment by filipefelice** [comment]
Problema resolvido, fechando essa issue.
Talvez iremos ter algum tipo de problema no aplicativo para android/ios ainda.
Na plataforma é recomendável sempre usar https://newschoolapp.com.br
