### ISSUE TITLE
Melhorar e centralizar criação e destruição dos cenários de testes e2e

### ISSUE THREAD

**Issue by pethersonmoreno** [NewSchoolApp/newschool-backend#161]
Acho que poderíamos criar um utils pra isso, imagino que todos afterAll vão ter isso né

_Originally posted by @DavideCarvalho in https://github.com/NewSchoolApp/newschool-backend/pull/154/files_

**Comment by DavideCarvalho** [comment]
Conseguimos fazer isso! Finalmente tirar aquela lógica toda uasdhuasdh
